### ISSUE TITLE
Can reds support fuzzy searching?

### ISSUE THREAD

**Issue by wxlfight** [tj/reds#38]
For example ，index three words "abcde","bcdefg","abcd".  Then i search "abc" get the result "abcde" "abcd" or when i search "cde" get the result "abcde" "bcdefg"

**Comment by plus-** [comment]
I don't think it's possible to do it at search time because of the way it's implemented using redis (exact match required). This is because the intended goal of the library was to search for words in a text, and not for an autocomplete feature.

However, I think an acceptable solution would be to multiply the indexed words to include their subsequences.

**Comment by wxlfight** [comment]
Yes, thank you for you reply.
