### ISSUE TITLE
I want this to support Chinese

### ISSUE THREAD

**Issue by xbl** [tj/reds#8]
I want this to support Chinese.How can I do it ?

**Comment by loretoparisi** [comment]
@xbl regarding multi-language support, maybe you would like to expose the stemming algorithm so that would be possible to add more languages externally, maybe using the good NodeNatural - https://github.com/NaturalNode/natural that recently has added support for non word boundary supported languages (like Chinese, Japanese, etc.). This will also let to handle the deaccent and more in general the unicode /double byte problem.

Hope this helps.

**Comment by stockholmux** [comment]
@loretoparisi Thanks for re-surfacing this (very old) issue. We actually allow for the overriding of the NLP processing see the [Extending](https://github.com/tj/reds#extending-reds) section. That being said, you can sub-in whatever you'd like (including the new Natural library which is used internally, although I'm hesitant to just update as it can break existing indexes).

**Comment by loretoparisi** [comment]
@stockholmux thanks, could you make a concrete example how to `yourNlpProcessingFunction` should be, so that I could make a test using my stemmer functions? Thanks.

**Comment by stockholmux** [comment]
Check out the [article I wrote](https://medium.com/@stockholmux/reds-internals-searching-and-better-searching-with-node-js-and-redis-57da99077e83) on it a while back and take a look at the original [`nlpProcess` function](https://github.com/tj/reds/blob/master/lib/reds.js#L79). To implement a new stemmer, you would just need to replace the `words` section with whatever stemming logic you need (`words` should just be an array of stemmed words). It's pretty easy if you play with it and `console.log` the current version. Hope it helps.
